"""Adding assetId foreign key to task

Revision ID: 6b1f15aa4e44
Revises: 9681deccc836
Create Date: 2019-07-14 18:36:28.690104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1f15aa4e44'
down_revision = '9681deccc836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assetId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'asset', ['assetId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'assetId')
    # ### end Alembic commands ###
